### ISSUE TITLE
SSL/TLS

### ISSUE THREAD

**Issue by devisscher** [YOWCT/SnapHole-AppStore#2]
Needs to be done before we can obtain an API Key.

**Comment by DenisCarriere** [comment]
Yep! We can probably tackle that tonight

**Comment by devisscher** [comment]
This is just for the front-facing site, I don't think they know that the app is relying on https://api.snaphole.io as opposed to http://snaphole.io. Nonetheless both should be secure.

**Comment by DenisCarriere** [comment]
haha! Yea I know.. people are 😜

Both sites are now running over SSL 🎉 

![image](https://user-images.githubusercontent.com/550895/29344655-5ac3cc7a-8207-11e7-85f9-961ac3016aa1.png)
