### ISSUE TITLE
Map background as grey

### ISSUE THREAD

**Issue by hedonisticeric** [YOWCT/SnapHole-AppStore#4]
Can we adjust the backgound of the map to use a greyscale default? It will make the pin pop out more.

**Comment by DenisCarriere** [comment]
We can do anything we want! 👍 

The map style was more of a placeholder until we design a "nice looking" map style using MapboxStudio:
https://www.mapbox.com/studio/

Here's one of the light greyscale styles

https://api.mapbox.com/styles/v1/mapbox/light-v9.html?fresh=true&title=true&access_token=pk.eyJ1IjoiYWRkeHkiLCJhIjoiY2lsdmt5NjZwMDFsdXZka3NzaGVrZDZtdCJ9.ZUE-LebQgHaBduVwL68IoQ#13.59/45.4168/-75.6869

![image](https://user-images.githubusercontent.com/550895/29488349-d7df770a-84d6-11e7-83d5-d9649b20fd20.png)

**Comment by hedonisticeric** [comment]
Yesss! This one looks perfect

**Comment by DenisCarriere** [comment]
Ok I added the Mapbox GL greyscale map.

The map related code is still very easy to read:

```js
mapboxgl.accessToken = 'pk.eyJ1IjoiYWRkeHkiLCJhIjoiY2lsdmt5NjZwMDFsdXZka3NzaGVrZDZtdCJ9.ZUE-LebQgHaBduVwL68IoQ';
const map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/light-v9',
    center: [-75.6972, 45.4215],
    zoom: 11,
    scrollZoom: false,
    doubleClickZoom: true,
});
const nav = new mapboxgl.NavigationControl();
map.addControl(nav, 'top-left');
```

![image](https://user-images.githubusercontent.com/550895/29489390-252aa14e-84ee-11e7-935a-c21511116c34.png)
